config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create' , as: :log_in
  delete 'sessions/destroy' , as: :log_out
  post 'events/invite' ,as: :invite
  resources :users, only: [:new,:show, :create]
  resources :events, except: [:edit, :update]
  root  to: "sessions#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :event_attendee, class_name: 'User'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, source: :event_attendee,
                       through: :attendances, dependent: :destroy
  validates :description, :event_date, presence: true

  scope :past, -> { where('event_date < ?', Time.now) }
  scope :upcoming, -> { where('event_date >= ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :username, presence: true, uniqueness: true
  has_many :events, foreign_key: :creator_id
  has_many :attendances, foreign_key: :event_attendee_id
  has_many :attended_events, through: :attendances

  def upcoming_events
    attended_events.where('event_date > ?', Time.now)
  end

  def past_events
    attended_events.where('event_date<?', Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_user!
    redirect_to sessions_new_path if current_user.nil?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def sign_in(user)
    session[:user_id] = user.id
    flash[:success] = 'Successfuly Logged in!'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create index show]
  def new
    @event = Event.new
  end

  def invite
    @event = Event.find(params[:event_id])
    user = User.find_by(username: params[:username])
    if !user.nil?
      if @event.attendees.include?(user)
        flash[:danger] = "#{params[:username].capitalize} is already invited"
      else
        @event.attendees << user
        flash[:success] = "#{params[:username].capitalize} successfuly invited!"
      end
    else
      flash[:danger] = 'No such user exits'
    end
    redirect_to @event
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
      flash[:success] = 'Event successfuly created!'
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    if current_user == @event.creator || @event.event_attendees
        .include?(current_user)
    else
      redirect_to current_user
    end
  end

  def index
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def event_params
    params.require(:event)
      .permit(:description, :event_date, :username, :event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params['user']['username'])
    if user
      sign_in(user)
      redirect_to user_path(user)
    else
      flash[:danger] = 'Invalid user name!'
      redirect_to sessions_new_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You are successful logged out!'
    redirect_to sessions_new_path
  end

  def sign_in(user)
    session[:user_id] = user.id
    flash[:success] = 'Successfuly Logged in!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authenticate_user!, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      sign_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @created_events = current_user.events
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to sessions_new_path if current_user.nil?
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    session[:user_id] = user.id
    flash[:success] = 'Successfuly Logged in!'
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d="
  end

  def error_flashes
    if flash[:danger]
      content_tag(:p, flash[:danger],
                  class: 'alert alert-danger my-3 p-3')
    elsif flash[:success]
      content_tag(:p, flash[:success],
                  class: 'alert alert-success my-3 p-3')
    end
  end

  def logged_in_private?
    if signed_in?
      link_to current_user.username.capitalize,
              current_user, class: 'navbar-brand'
    else
      content_tag(:p, PrivateEvents,
                  class: 'navbar-brand')
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def logged_in_user_log?
    if signed_in?
      link_to 'Log out', log_out_path, class: 'nav-link nav-item',
                                       method: :delete, data: {
                                         confirmation: 'Are you sure?'
                                       }
    else
      link_to 'Sign Up', new_user_path, class: 'nav-link nav-item'
    end
  end

  def logged_in_user_all_events?
    if signed_in?
      link_to 'All Events', events_path, class: 'nav-link nav-item'
    else
      link_to 'Login', sessions_new_path, class: 'nav-link nav-item'
    end
  end

  def logged_in_user_create_event?
    if signed_in?
      link_to 'Create Event', new_event_path,
              class: 'nav-link nav-item'
    end
  end

  def logged_in_user_avatar?
    image_tag avatar_url(current_user) if signed_in?
  end
end

app/views/events/index.html.erb
<h1 class="title mx-auto">All Events</h1>

<h2>Upcoming Events</h2>
<div>
  <% @upcoming_events.each do |event| %>
    <p class="jumbotron p-3 bg-info text-light lead mt-1"><%= event.description %> @<%= event.event_date %></p>
  <% end %>
</div>

<h2 class="">Past Events</h2>

<div class="mt-2">
  <% @past_events.each do |event| %>
    <p class="jumbotron p-3 alert-danger text-dark lead"><%= event.description %> @<%= event.event_date %></p>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create Event</h1>
<%if @event.errors%>
<%@event.errors.full_messages.each do |error|%>
<div class="alert alert-danger"><%=error%></div>
<%end%>
<%end%>

<%= form_for @event do |f| %>
<fieldset class="form-group">
 <%= f.text_field :description ,class:'form-control',placeholder:'Description'%>
</fieldset>
<fieldset class="form-group">
 <%= f.date_field :event_date,class:'form-control',placeholder:'Event date' %>
</fieldset>
<%= f.submit class:'form-control btn btn-primary'%>

<% end %>

app/views/events/show.html.erb
<div class>
  <div class="d-flex justify-content-between align-content-center my-3 p-2 jumbotron">
    <p class="lead"><%= @event.description %></p>
    <p class="lead"><%= @event.event_date %></p>
    <p class="lead">Organised by <%= @event.creator.username.capitalize %></p>
  </div>
  <h2 class="title">Event Attendees</h2>

   <% @event.attendees.each do |attendee|%>

   <p><%=attendee.username.capitalize%></p>
   <%end%>
  
 <%if @event.creator==current_user%>
  <div>
    <h2>Invite Freinds</h2>
      <%= form_tag invite_path do %>
     <div class="form-group">
      <%= text_field_tag "username",nil,class:"form-control",placeholder:"User Name"%>
    </div>
    <div class="form-group">
      <%=hidden_field_tag  "event_id" ,"#{@event.id}"%>
      <%=submit_tag 'Invite' ,class:"form-control btn btn-primary" %>
    </div>
    <%end%>
  </div>
 <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <%=logged_in_private?%>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <%=logged_in_user_log?%>
      <%=logged_in_user_all_events?%>
      <%=logged_in_user_create_event?%>
      <%=logged_in_user_avatar?%>
    </ul>
  </div>
</nav>
<div class="container">
  <%=error_flashes%>
</div>
   <div class="container"> 
   <%= yield %>
   </div>
  </body>
</html>

app/views/users/new.html.erb
<%if @user.errors%>
<%@user.errors.full_messages.each do |error|%>
<div class="alert alert-danger "><%=error %></div>
<%end%>
<%end%>

<div class='p-3 m-3 col-md-6 mx-auto mt-5'>
<h2 class="h2 py-3 mx-auto">Please Sign up</h2>
 <%= form_for @user do |f| %>
 <fieldset class="form-group">
  <%= f.text_field :username ,class:'form-control',placeholder:'User Name', autofocus:true%>
 </fieldset>
 <fieldset class="form-group">
  <%= f.email_field :email ,class:'form-control',placeholder:'Email'%>
 </fieldset>
 <%= f.submit class:'form-control btn btn-primary' %>
 
 <% end %>
<p class="my-3"> Already registered? <%= link_to  "Log in", sessions_new_path %></p>
</div>

app/views/users/show.html.erb
<h2 class="mt-3">Events You Created</h2>
<%if current_user.events.count>0%>
<% @created_events.each do |event| %>
 <p class="bg-info rounded py-3"> 
  <%= link_to  event.description, event_path(event) ,class:'lead text-light py-5 px-3'%>
 </p>
<% end %>
<%else%>
<p class="lead">You created zero events</p>
<%end%>


<h2> Upcoming events to attend</h2>
<%if current_user and current_user.upcoming_events.count>0%>
 You have <%= pluralize(current_user.upcoming_events.count,'event')%> to attend.
<div class="d-flex flex-column">
  <%@current_user.upcoming_events.each do |event|%>
   <p class="jumbotron d-flex justify-content-between py-2 my-2">
   <span> <%= link_to  event.description, event_path(event) %></span>
   <span> ON: <%=event.event_date.strftime('%FT%T')%></span>
   <span> BY:  <%=event.creator.username.capitalize%></span>
   </p>
  <%end%>
</div>
<%else%>
<p class ="lead">You have no events to attend</p>
<%end%>

<h2>Past Events</h2>
<%if current_user and current_user.past_events.count>0%>
 You have <%= pluralize(current_user.past_events.count,'event')%> past events.
<div class="d-flex flex-column">
  <%@current_user.past_events.each do |event|%>
   <p class="jumbotron d-flex justify-content-between py-2 my-2 alert-danger">
   <span> <%= link_to  event.description, event_path(event) %></span>
   <span> ON: <%=event.event_date%></span>
   <span> BY:  <%=event.creator.username.capitalize%></span>
   </p>
  <%end%>
</div>
<%else%>
<p class ="lead">You have no past events</p>
<%end%>